# Generated by Django 4.0.1 on 2022-02-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='date_assigned',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='date_returned',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_maintained',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='purchase_date',
            field=models.DateField(),
        ),
    ]
