# Generated by Django 4.0.1 on 2022-02-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_device_device_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='license_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='order_number',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
