# Generated by Django 4.0.1 on 2022-02-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_device_assignment_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='assigned_by',
            field=models.CharField(choices=[(1, 'Lawerh Caesar'), (2, 'Gabriel Muhammad'), (3, 'Anthony Kwawu'), (4, 'Symplice Athodjinou'), (5, 'Christopher Hanson'), (6, 'Nausheen Siddiqi')], default='Not Assigned', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='assigned_to',
            field=models.CharField(default='Not Assigned', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Phone', 'Phone'), ('Network Device', 'Network Device'), ('Router', 'Router'), ('TV', 'TV'), ('Misc', 'Misc'), ('Printer', 'Printer'), ('Desktop', 'Desktop'), ('Tablet', 'Tablet'), ('Intercom', 'Intercom'), ('Accessories', 'Accessories'), ('Hard Cover', 'Hard Cover'), ('Bags', 'Bags'), ('Camera', 'Camera')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_location',
            field=models.CharField(default='N/A', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='maintained_by',
            field=models.CharField(default='N/A', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='order_number',
            field=models.CharField(default='N/A', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_no',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
