# Generated by Django 4.0.1 on 2022-02-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_device_assigned_by_alter_device_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='choose_item',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Phone', 'Phone'), ('Network Device', 'Network Device'), ('Router', 'Router'), ('TV', 'TV'), ('Misc', 'Misc'), ('Printer', 'Printer'), ('Desktop', 'Desktop'), ('Tablet', 'Tablet'), ('Intercom', 'Intercom'), ('Accessories', 'Accessories'), ('Hard Cover', 'Hard Cover'), ('Bags', 'Bags'), ('Camera', 'Camera')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='device_condition',
            field=models.CharField(choices=[(1, 'Excellent'), (2, 'Good'), (3, 'Broken'), (4, 'Dented'), (5, 'Ugly'), (6, 'Missing Accessory'), (7, 'Other')], max_length=1000),
        ),
    ]
