# Generated by Django 4.0.1 on 2022-02-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_maintenance_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.CharField(blank=True, default='Not Assigned', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='assigned_by',
            field=models.CharField(blank=True, choices=[('Lawerh Caesar', 'Lawerh Caesar'), ('Gabriel Muhammad', 'Gabriel Muhammad'), ('Anthony Kwawu', 'Anthony Kwawu'), ('Symplice Athodjinou', 'Symplice Athodjinou'), ('Christopher Hanson', 'Christopher Hanson'), ('Nausheen Siddiqi', 'Nausheen Siddiqi')], default='Not Assigned', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='assigned_to',
            field=models.CharField(blank=True, default='Not Assigned', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='assignment_reason',
            field=models.CharField(blank=True, choices=[('Loaner', 'Loaner'), ('Regular', 'Regular'), ('Short Term', 'Short Term'), ('Long Term', 'Long Term'), ('Other', 'Other')], default='Loaner', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.CharField(blank=True, choices=[('Laptop', 'Laptop'), ('Phone', 'Phone'), ('Network Device', 'Network Device'), ('Router', 'Router'), ('TV', 'TV'), ('Misc', 'Misc'), ('Printer', 'Printer'), ('Desktop', 'Desktop'), ('Tablet', 'Tablet'), ('Intercom', 'Intercom'), ('Accessories', 'Accessories'), ('Hard Cover', 'Hard Cover'), ('Bags', 'Bags'), ('AIO', 'AIO'), ('Camera', 'Camera'), ('-', '-')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='date_assigned',
            field=models.CharField(blank=True, default='N/A', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='date_returned',
            field=models.CharField(blank=True, default='N/A', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_location',
            field=models.CharField(blank=True, default='N/A', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_name',
            field=models.CharField(blank=True, default='N/A', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='known_issues',
            field=models.CharField(blank=True, default='N/A', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_maintained',
            field=models.CharField(blank=True, default='N/A', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='license_expiry',
            field=models.CharField(blank=True, default='N/A', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='machine_condition',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Broken', 'Broken'), ('Dented', 'Dented'), ('Ugly', 'Ugly'), ('Missing Accessory', 'Missing Accessory'), ('Other', 'Other')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='maintained_by',
            field=models.CharField(blank=True, default='N/A', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='order_number',
            field=models.CharField(blank=True, default='N/A', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='purchase_date',
            field=models.CharField(blank=True, default='N/A', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_no',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='antivirus_license',
            field=models.CharField(choices=[('Expired', 'Expired'), ('Active', 'Active')], default='N/A', max_length=1000),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='choose_item',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Phone', 'Phone'), ('Network Device', 'Network Device'), ('Router', 'Router'), ('TV', 'TV'), ('Misc', 'Misc'), ('Printer', 'Printer'), ('Desktop', 'Desktop'), ('Tablet', 'Tablet'), ('Intercom', 'Intercom'), ('Accessories', 'Accessories'), ('Hard Cover', 'Hard Cover'), ('Bags', 'Bags'), ('AIO', 'AIO'), ('Camera', 'Camera'), ('-', '-')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='cover_inspection',
            field=models.CharField(choices=[('Done', 'Done'), ('Not Done', 'Not Done')], default='Not Done', max_length=1000),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='device_condition',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Broken', 'Broken'), ('Dented', 'Dented'), ('Ugly', 'Ugly'), ('Missing Accessory', 'Missing Accessory'), ('Other', 'Other')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='dust_inspection',
            field=models.CharField(choices=[('Done', 'Done'), ('Not Done', 'Not Done')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='system_license',
            field=models.CharField(choices=[('Expired', 'Expired'), ('Active', 'Active')], default='N/A', max_length=1000),
        ),
    ]
