# Generated by Django 4.0.1 on 2022-04-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_device_category_alter_maintenance_choose_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.CharField(blank=True, choices=[('Laptop', 'Laptop'), ('Macbook', 'Macbook'), ('Phone', 'Phone'), ('Network Device', 'Network Device'), ('Router', 'Router'), ('TV', 'TV'), ('Misc', 'Misc'), ('Printer', 'Printer'), ('Desktop', 'Desktop'), ('Tablet', 'Tablet'), ('Intercom', 'Intercom'), ('Accessories', 'Accessories'), ('Hard Cover', 'Hard Cover'), ('Bags', 'Bags'), ('AIO', 'AIO'), ('Camera', 'Camera'), ('IMAC', 'IMAC'), ('ID Card Printer', 'ID Card Printer')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='choose_item',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Macbook', 'Macbook'), ('Phone', 'Phone'), ('Network Device', 'Network Device'), ('Router', 'Router'), ('TV', 'TV'), ('Misc', 'Misc'), ('Printer', 'Printer'), ('Desktop', 'Desktop'), ('Tablet', 'Tablet'), ('Intercom', 'Intercom'), ('Accessories', 'Accessories'), ('Hard Cover', 'Hard Cover'), ('Bags', 'Bags'), ('AIO', 'AIO'), ('Camera', 'Camera'), ('IMAC', 'IMAC'), ('ID Card Printer', 'ID Card Printer')], max_length=1000),
        ),
    ]
