# Generated by Django 4.0.1 on 2022-05-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='device_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Primary Staff', 'Primary Staff'), ('Secondary Staff', 'Secondary Staff'), ('Auxiliary Staff', 'Auxiliary')], max_length=100, null=True),
        ),
    ]
